plt.plot(t_euleri,T_euleri)
plt.title('Évolution de la température en fonction du temps')
plt.xlabel('Temps (s)')
plt.ylabel('Température (K)')
plt.show()
plt.plot(t_euleri,X_euleri)
plt.title('Évolution de Xr en fonction du temps')
plt.xlabel('Temps (s)')
plt.ylabel('Xr')
plt.show()